call ..\setdirs.bat
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk milesmid.c
%WINDOWS_PLATFORM_SDK%\bin\rc.exe -i%MSVC8Dir%\vc\atlmfc\include -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include" -nologo -I..\sdk -fo milesmid.res milesmid.rc
%MSVC8Dir%\vc\bin\link.exe -out:milesmid.exe -fixed  -nologo -opt:ref -map -libpath:%MSVC8Dir%\vc\lib -LIBPATH:%DXSDK_DIR%\lib\x86 -libpath:%WINDOWS_PLATFORM_SDK%\lib -libpath:"%MSVC8Dir%\dia sdk\lib" -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release -pdb:milesmid.pdb -LTCG milesmid.obj milesmid.res user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib -libpath:..\..\lib mss32.lib mss32midi.lib shell32.lib comdlg32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk makeloop.cpp
%MSVC8Dir%\vc\bin\link.exe -out:makeloop.exe -fixed    -nologo -opt:ref -map -libpath:%MSVC8Dir%\vc\lib -LIBPATH:%DXSDK_DIR%\lib\x86 -libpath:%WINDOWS_PLATFORM_SDK%\lib -libpath:"%MSVC8Dir%\dia sdk\lib" -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release -pdb:makeloop.pdb -LTCG makeloop.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib -libpath:..\..\lib mss32.lib mss32midi.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk wavmux.cpp
%MSVC8Dir%\vc\bin\link.exe -out:wavmux.exe -fixed    -nologo -opt:ref -map -libpath:%MSVC8Dir%\vc\lib -LIBPATH:%DXSDK_DIR%\lib\x86 -libpath:%WINDOWS_PLATFORM_SDK%\lib -libpath:"%MSVC8Dir%\dia sdk\lib" -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release -pdb:wavmux.pdb -LTCG wavmux.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib -libpath:..\..\lib mss32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk milesply.cpp
%WINDOWS_PLATFORM_SDK%\bin\rc.exe -i%MSVC8Dir%\vc\atlmfc\include -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include" -nologo -I..\sdk -fo milesply.res milesply.rc
%MSVC8Dir%\vc\bin\link.exe -out:milesply.exe -fixed  -nologo -opt:ref -map -libpath:%MSVC8Dir%\vc\lib -LIBPATH:%DXSDK_DIR%\lib\x86 -libpath:%WINDOWS_PLATFORM_SDK%\lib -libpath:"%MSVC8Dir%\dia sdk\lib" -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release -pdb:milesply.pdb -LTCG milesply.obj milesply.res user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib -libpath:..\..\lib mss32.lib mss32midi.lib comdlg32.lib comctl32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk midiechw.cpp
%WINDOWS_PLATFORM_SDK%\bin\rc.exe -i%MSVC8Dir%\vc\atlmfc\include -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include" -nologo -I..\sdk -fo midiechw.res midiechw.rc
%MSVC8Dir%\vc\bin\link.exe -out:midiechw.exe -fixed  -nologo -opt:ref -map -libpath:%MSVC8Dir%\vc\lib -LIBPATH:%DXSDK_DIR%\lib\x86 -libpath:%WINDOWS_PLATFORM_SDK%\lib -libpath:"%MSVC8Dir%\dia sdk\lib" -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release -pdb:midiechw.pdb -LTCG midiechw.obj midiechw.res user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib -libpath:..\..\lib mss32.lib mss32midi.lib winmm.lib dsound.lib comdlg32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk bankdump.cpp
%MSVC8Dir%\vc\bin\link.exe -out:bankdump.exe -fixed    -nologo -opt:ref -map -libpath:%MSVC8Dir%\vc\lib -LIBPATH:%DXSDK_DIR%\lib\x86 -libpath:%WINDOWS_PLATFORM_SDK%\lib -libpath:"%MSVC8Dir%\dia sdk\lib" -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release -pdb:bankdump.pdb -LTCG bankdump.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib -libpath:..\..\lib mss32.lib -LIBPATH:C:/devel/projects/mss/build/win
