call ..\setdirs.bat
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -D__RADINEXE__ -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include  -I..\sdk asifile.cpp
%MSVC8Dir%\vc\bin\amd64\link.exe -out:asifile.exe -fixed    -nologo -map -opt:ref -libpath:%MSVC8Dir%\vc\lib\amd64 -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\amd64 -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -nodefaultlib -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -LTCG asifile.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss64.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -D__RADINEXE__ -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include  -I..\sdk sstest.c
%MSVC8Dir%\vc\bin\amd64\link.exe -out:sstest.exe -fixed    -nologo -map -opt:ref -libpath:%MSVC8Dir%\vc\lib\amd64 -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\amd64 -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -nodefaultlib -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -LTCG sstest.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss64.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -D__RADINEXE__ -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include  -I..\sdk digplay.c
%MSVC8Dir%\vc\bin\amd64\link.exe -out:digplay.exe -fixed    -nologo -map -opt:ref -libpath:%MSVC8Dir%\vc\lib\amd64 -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\amd64 -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -nodefaultlib -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -LTCG digplay.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss64.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -D__RADINEXE__ -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include  -I..\sdk dbtest.c
%MSVC8Dir%\vc\bin\amd64\link.exe -out:dbtest.exe -fixed    -nologo -map -opt:ref -libpath:%MSVC8Dir%\vc\lib\amd64 -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\amd64 -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -nodefaultlib -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -LTCG dbtest.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss64.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -D__RADINEXE__ -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include  -I..\sdk play.c
%MSVC8Dir%\vc\bin\amd64\link.exe -out:play.exe -fixed    -nologo -map -opt:ref -libpath:%MSVC8Dir%\vc\lib\amd64 -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\amd64 -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -nodefaultlib -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -LTCG play.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss64.lib mss64midi.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -D__RADINEXE__ -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include  -I..\sdk streamer.c
%MSVC8Dir%\vc\bin\amd64\link.exe -out:streamer.exe -fixed    -nologo -map -opt:ref -libpath:%MSVC8Dir%\vc\lib\amd64 -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\amd64 -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -nodefaultlib -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -LTCG streamer.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss64.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -D__RADINEXE__ -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include  -I..\sdk dlsplay.c
%MSVC8Dir%\vc\bin\amd64\link.exe -out:dlsplay.exe -fixed    -nologo -map -opt:ref -libpath:%MSVC8Dir%\vc\lib\amd64 -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\amd64 -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -nodefaultlib -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -LTCG dlsplay.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss64.lib mss64midi.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -D__RADINEXE__ -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include  -I..\sdk filter.cpp
%MSVC8Dir%\vc\bin\amd64\link.exe -out:filter.exe -fixed    -nologo -map -opt:ref -libpath:%MSVC8Dir%\vc\lib\amd64 -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\amd64 -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -nodefaultlib -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -LTCG filter.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss64.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -D__RADINEXE__ -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include  -I..\sdk multiflt.cpp
%MSVC8Dir%\vc\bin\amd64\link.exe -out:multiflt.exe -fixed    -nologo -map -opt:ref -libpath:%MSVC8Dir%\vc\lib\amd64 -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\amd64 -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -nodefaultlib -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -LTCG multiflt.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss64.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -D__RADINEXE__ -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include  -I..\sdk record.c
%MSVC8Dir%\vc\bin\amd64\link.exe -out:record.exe -fixed    -nologo -map -opt:ref -libpath:%MSVC8Dir%\vc\lib\amd64 -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\amd64 -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -nodefaultlib -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -LTCG record.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss64.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -D__RADINEXE__ -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include  -I..\sdk eventtest.cpp
%MSVC8Dir%\vc\bin\amd64\link.exe -out:eventtest.exe -fixed    -nologo -map -opt:ref -libpath:%MSVC8Dir%\vc\lib\amd64 -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\amd64 -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -nodefaultlib -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -LTCG eventtest.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss64.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -D__RADINEXE__ -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include  -I..\sdk sidechain.cpp
%MSVC8Dir%\vc\bin\amd64\link.exe -out:sidechain.exe -fixed    -nologo -map -opt:ref -libpath:%MSVC8Dir%\vc\lib\amd64 -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\amd64 -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -nodefaultlib -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -LTCG sidechain.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss64.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -D__RADINEXE__ -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include  -I..\sdk demo.c
%WINDOWS_PLATFORM_SDK%\bin\rc.exe -i%MSVC8Dir%\vc\atlmfc\include -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include -nologo -I..\sdk -fo demo.res demo.rc
%MSVC8Dir%\vc\bin\cvtres.exe /nologo /machine:X64 -out:C:/devel/projects/mss/build/win64/temps/exe64/LTCG/demo/demo.res.obj demo.res
%MSVC8Dir%\vc\bin\amd64\link.exe -out:demo.exe -fixed  -nologo -map -opt:ref -libpath:%MSVC8Dir%\vc\lib\amd64 -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\amd64 -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -nodefaultlib -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -LTCG demo.obj C:\devel\projects\mss\build\win64\temps\exe64\LTCG\demo\demo.res.obj user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss64.lib mss64midi.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -D__RADINEXE__ -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include  -I..\sdk examms.cpp
%WINDOWS_PLATFORM_SDK%\bin\rc.exe -i%MSVC8Dir%\vc\atlmfc\include -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include -nologo -I..\sdk -fo examms.res examms.rc
%MSVC8Dir%\vc\bin\cvtres.exe /nologo /machine:X64 -out:C:/devel/projects/mss/build/win64/temps/exe64/LTCG/examms/examms.res.obj examms.res
%MSVC8Dir%\vc\bin\amd64\link.exe -out:examms.exe -fixed  -nologo -map -opt:ref -libpath:%MSVC8Dir%\vc\lib\amd64 -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\amd64 -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -nodefaultlib -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -LTCG examms.obj C:\devel\projects\mss\build\win64\temps\exe64\LTCG\examms\examms.res.obj user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss64.lib comctl32.lib comdlg32.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -D__RADINEXE__ -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include  -I..\sdk quick.c
%WINDOWS_PLATFORM_SDK%\bin\rc.exe -i%MSVC8Dir%\vc\atlmfc\include -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include -nologo -I..\sdk -fo quick.res quick.rc
%MSVC8Dir%\vc\bin\cvtres.exe /nologo /machine:X64 -out:C:/devel/projects/mss/build/win64/temps/exe64/LTCG/quick/quick.res.obj quick.res
%MSVC8Dir%\vc\bin\amd64\link.exe -out:quick.exe -fixed  -nologo -map -opt:ref -libpath:%MSVC8Dir%\vc\lib\amd64 -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\amd64 -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -nodefaultlib -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -LTCG quick.obj C:\devel\projects\mss\build\win64\temps\exe64\LTCG\quick\quick.res.obj user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss64.lib mss64midi.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -D__RADINEXE__ -I%MSVC8Dir%\vc\include -I%WINDOWS_PLATFORM_SDK%\include -I%DXSDK_DIR%\include  -I..\sdk eax4exam.cpp
%MSVC8Dir%\vc\bin\amd64\link.exe -out:eax4exam.exe -fixed  -nologo -map -opt:ref -libpath:%MSVC8Dir%\vc\lib\amd64 -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\x64 -libpath:%WINDOWS_PLATFORM_SDK%\lib\amd64 -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -nodefaultlib -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -LTCG eax4exam.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss64.lib -LIBPATH:C:/devel/projects/mss/build/win64
